### ISSUE TITLE
ordhook stuck in indexing inscriptions and never send any data to my endpoint

### ISSUE THREAD

**Issue by wycl16514** [hirosystems/bitcoin-indexer#248]
dear friends:

I am new to ordhook and trying ordhook to stream ordinal activities to my endpoint, I used a CHAINSTACK endpoint, and following is my Ordhook.toml:

```toml
[storage]
working_dir = "ordhook"

# [http_api]
# http_port = 20456

[network]
mode = "mainnet"
bitcoind_rpc_url = "http://IP:PORT"
bitcoind_rpc_username = "XXXXXXX"
bitcoind_rpc_password = "XXXXXX"

bitcoind_zmq_url = "tcp://IP:PORT"


[limits]
max_number_of_bitcoin_predicates = 100
max_number_of_concurrent_bitcoin_scans = 100
max_number_of_processing_threads = 16
bitcoin_concurrent_http_requests_max = 16
max_caching_memory_size_mb = 32000


[bootstrap]
download_url = "https://archive.hiro.so/mainnet/ordhook/mainnet-ordhook-sqlite-latest"

[logs]
ordinals_internals = true
chainhook_internals = true
```

because Ordhook can't use a https endpoint, therefore I used nginx as proxy, 47.128.200.237 is the ip of my nginx server. I used the following command to start the service:

ordhook service start --post-to=http://localhost:3000/api/events --config-path=./Ordhook.toml

and the service stuck in the following state and without sending any data to my endpoint:

![image](https://github.com/hirosystems/ordhook/assets/7506958/c8f992ee-1bac-4051-916c-eb4d6c76fe32)

I guest the problem lies in the field bitcoind_zmq_url = "tcp://IP:PORT", I saw from the doc that, this field is set to tcp://0.0.0.0:18543, which means the bitcoin node should locate at the same machine as ordhook, but I don't have a full bitcoin node in my local and I have to use a remote bitcoin service.

Do you know what's my problem, how can I fix that, I am highly appreciate your help, thank you very much.
