### ISSUE TITLE
Indexer inside Docker Compose - Unable to open db: unable to read hord.rocksdb: IO error

### ISSUE THREAD

**Issue by GregorWedlich** [hirosystems/bitcoin-indexer#525]
I will run the bitcoin-indexer in a docker compose file. i get the following error:

```
bitcoin-indexer           | {"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-02T21:34:29.503563961Z"}
```

```
...
  bitcoin-indexer:
    image: hirosystems/bitcoin-indexer:latest
    container_name: bitcoin-indexer
    restart: unless-stopped
    networks:
      - indexer-network
      - bitcoin-net
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.toml:/config/config.toml
      - bitcoin-indexer-data:/data
    command: "ordinals service start --config-path /config/config.toml"
    ports:
      - "9153:9153"  # Prometheus metrics
...
```

My config.toml:

```
[bitcoind]
network = "mainnet"
rpc_url = "http://bitcoin:8332"
rpc_username = "${RPC_USER}"
rpc_password = "${RPC_PASSWORD}"
zmq_url = "tcp://bitcoin:28332"

[ordinals.db]
database = "ordinals"
host = "postgres"
port = 5432
username = "postgres"
password = ""

[ordinals.meta_protocols.brc20]
enabled = true
lru_cache_size = 50000

[ordinals.meta_protocols.brc20.db]
database = "brc20"
host = "postgres"
port = 5432
username = "postgres"
password = ""

[runes]
lru_cache_size = 50000

[runes.db]
database = "runes"
host = "postgres"
port = 5432
username = "postgres"
password = ""

[resources]
ulimit = 4096
cpu_core_available = 4
memory_available = 16
bitcoind_rpc_threads = 4
bitcoind_rpc_timeout = 15

[storage]
working_dir = "/data"

[metrics]
enabled = true
prometheus_port = 9153
```
