### ISSUE TITLE
How do I run the program?

### ISSUE THREAD

**Issue by zhangqichuan** [hirosystems/bitcoin-indexer#537]
# bitcoin-indexer ordinals service start --config-path ./Indexer.toml
{"msg":"Running ordinals DB migrations","level":"INFO","ts":"2025-05-20T07:36:23.889500881Z"}
{"msg":"Running brc20 DB migrations","level":"INFO","ts":"2025-05-20T07:36:23.898306915Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-20T07:36:43.963339993Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-20T07:36:53.963735844Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-20T07:37:03.964122812Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-20T07:37:13.964531558Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-20T07:37:23.964953641Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-20T07:37:33.965358649Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-20T07:37:43.965775449Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-20T07:37:53.966157831Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /data/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-05-20T07:38:03.966662852Z"}

**Comment by zhangqichuan** [comment]
Hi，team. How do I solve this problem?

**Comment by ASuciuX** [comment]
Hi @zhangqichuan,
I believe this might be related to your configuration. Could you please share the steps you followed to set up and run the Bitcoin indexer with Ordinals?

Please include the commands you've run and your OS.

**Comment by QuantProcessing** [comment]
@ASuciuX I have same problem. 

My docker-compose.yaml
```
  ...
  postgres:
    image: postgres:17
    container_name: postgres-indexer
    networks:
      - indexer-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  bitcoin-indexer:
    image: hirosystems/bitcoin-indexer:latest
    container_name: bitcoin-indexer
    restart: unless-stopped
    networks:
      - indexer-network 
      - default          
    depends_on:
      postgres:
        condition: service_healthy
      bitcoind:
        condition: service_healthy
    volumes:
      - ./bitcoin-indexer/config.toml:/config/config.toml:ro
      - /data2/bitcoin-indexer:/workspace
    command: "ordinals service start --config-path /config/config.toml"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
  ...
```

This is config.toml
```
[storage]
working_dir = "/workspace"

[metrics]
enabled = true
prometheus_port = 9153

[ordinals.db]
database = "ordinals"
host = "postgres-indexer"  # 使用新的容器名
port = 5432
username = "postgres"
password = "postgres"

[ordinals.meta_protocols.brc20]
enabled = true
lru_cache_size = 10000

[ordinals.meta_protocols.brc20.db]
database = "brc20"
host = "postgres-indexer"
port = 5432
username = "postgres"
password = "postgres"

[runes]
lru_cache_size = 10000

[runes.db]
database = "runes"
host = "postgres-indexer"
port = 5432
username = "postgres"
password = "postgres"

[bitcoind]
network = "mainnet"
rpc_url = "http://bitcoind:8332"
rpc_username = "{{rpc_name}}"
rpc_password = "{{rpc_pass}}"
zmq_url = "tcp://bitcoind:28332"

[resources]
ulimit = 2048
cpu_core_available = 6
memory_available = 16
bitcoind_rpc_threads = 2
bitcoind_rpc_timeout = 15 
```

And, this is face error:
```
ry. Retrying in 10s","level":"WARN","ts":"2025-06-24T06:29:30.604503947Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /workspace/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-06-24T06:29:40.604803086Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /workspace/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-06-24T06:29:50.605102577Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /workspace/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-06-24T06:30:00.605572476Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /workspace/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-06-24T06:30:10.605878351Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /workspace/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-06-24T06:30:20.606186125Z"}
{"msg":"Unable to open db: unable to read hord.rocksdb: IO error: No such file or directory: While opening a file for sequentially reading: /workspace/hord.rocksdb/CURRENT: No such file or directory. Retrying in 10s","level":"WARN","ts":"2025-06-24T06:30:30.606463744Z"}
```

I login in to bitcoin-indexer container, and i find hord.rocksdb directory, but no CURRENT file.
